### ISSUE TITLE
While visiting saltpad it returns blank page (using v0.3 release version )

### ISSUE THREAD

**Issue by JaminZhang** [Lothiraldan/saltpad#158]
## 01. My salt-master and salt-api version are below:

```
[root@tracker-seeder ~]# rpm -qa salt-master salt-api
salt-master-2015.8.8-2.el6.noarch
salt-api-2015.8.8-2.el6.noarch

```

## 02. My salt-api conf is below:

```
[root@tracker-seeder master.d]# cat /etc/salt/master.d/salt-api.conf
rest_cherrypy:
  port: 8000
  host: 127.0.0.1     
  disable_ssl: true
  websockets: True
  cors_origin: '*'
  static: /data/www/saltpad/static
  static_path: /static
  app: /data/www/saltpad/index.html
  app_path: /saltpad

external_auth:
  pam:
    salt:
        - .*
        - '@runner'
        - '@wheel'

```

## 03. salt-api check result is below:

```
[root@tracker-seeder master.d]# curl -i -H accept=application/json -d username=salt -d password={mypassword} -d eauth=pam http://localhost:8000/login

{"return": [{"perms": [".*", "@runner", "@wheel"], "start": 1458380946.0947101, "token": "8dfa360e88d0641803929d602df668677c87cf34", "expire": 1458424146.0947101, "user": "salt", "eauth": "pam"}]}		
		
```

## 05. My settings.json is below:

```
[root@tracker-seeder saltpad]# cat /data/www/saltpad/config/settings.json 
{
    "API_URL": "localhost:8000",
    "SECURE_HTTP": false,
    "templates": {},
    "EAUTH": "pam",
    "FLAVOUR": "rest_cherrypy",
    "PATH_PREFIX": "/saltpad/"
}
```
## 06. curl localhost result is below:

```
[root@tracker-seeder master.d]# curl http://localhost
<!doctype html>
<html lang="en" data-framework="react">
	<head>
		<meta charset="utf-8">
		<title>SaltPad</title>
	<link href="/static/styles.css" rel="stylesheet"></head>
	<body>
		<div id="app"></div>
	<script src="/static/vendors.js"></script><script src="/static/app.js"></script></body>
</html>
```

## 07. When I visit the saltpad IP via Chrome Browser, it's a blank page.
And it's source code is below:

```
<!doctype html>
<html lang="en" data-framework="react">
	<head>
		<meta charset="utf-8">
		<title>SaltPad</title>
	<link href="/static/styles.css" rel="stylesheet"></head>
	<body>
		<div id="app"></div>
	<script src="/static/vendors.js"></script><script src="/static/app.js"></script></body>
</html>
```

And at the Chrome Console it displays:

```
Uncaught SyntaxError: Unexpected token <
app.js:1 Uncaught SyntaxError: Unexpected token <
```

Could you tell me where I am wrong and how can I get some logs adn debug info?

Thanks.

**Comment by Lothiraldan** [comment]
Hi @JaminZhang, there was a typo in the README and release description, the file settings.json must be in the static directory and not the config directory. Did the unzip of the archive created the directory for you?

Sorry for the inconvenience.

Huge 👍 for the very detailed bug report.

**Comment by JaminZhang** [comment]
@Lothiraldan Thanks for the reply and the fixes.

In the README, 
`wget https://github.com/Lothiraldan/saltpad/releases/download/v0.3/dist.zip`

The URL should be https://github.com/Lothiraldan/saltpad/releases/download/v0.3.1/dist.zip.

I just deploy the v0.3.1 release version. And the unzip of the archive creates the static directory now.

But I still get a blank page while visiting saltpad it via Chrome (using v0.3.1 release version).

Its source code is below:

```
<!doctype html>
<html lang="en" data-framework="react">
	<head>
		<meta charset="utf-8">
		<title>SaltPad</title>
	<link href="/static/styles.css" rel="stylesheet"></head>
	<body>
		<div id="app"></div>
	<script src="/static/vendors.js"></script><script src="/static/app.js"></script></body>
</html>
```

And at the Chrome Console it displays:
![saltpad-issue01](https://cloud.githubusercontent.com/assets/6756954/14666194/b520d646-070a-11e6-86ed-bfca89b945ad.png)


Could you tell me where I am wrong?


In this issue https://github.com/Lothiraldan/saltpad/issues/156, 
you mentioned two deployment options.
According the README, I use the "Rest_cherrypy single-app page deployment".

But I get confused about the bleow:
![saltpad-issue02](https://cloud.githubusercontent.com/assets/6756954/14667447/e75ef546-0711-11e6-80a8-622bce2eb0eb.png)


Could you help to check my salt-api conf and settings.json content, 
are they right for "Rest_cherrypy single-app page deployment"?

## My salt-api conf is below:
```

[root@tracker-seeder master.d]# cat /etc/salt/master.d/salt-api.conf
rest_cherrypy:
  port: 8000
  host: 127.0.0.1     
  disable_ssl: true
  websockets: True
  cors_origin: '*'
  static: /data/www/saltpad/static
  static_path: /static
  app: /data/www/saltpad/index.html
  app_path: /saltpad

external_auth:
  pam:
    salt:
        - .*
        - '@runner'
        - '@wheel'
```

## My settings.json is below:

```
[root@tracker-seeder saltpad]# cat /data/www/saltpad/config/settings.json 
{
    "API_URL": "localhost:8000",
    "SECURE_HTTP": false,
    "templates": {},
    "EAUTH": "pam",
    "FLAVOUR": "rest_cherrypy",
    "PATH_PREFIX": "/saltpad/"
}

```

## I use nginx, and deploy the saltpad v0.3.1 to /data/www/saltpad/
