### ISSUE TITLE
got a problem during deploy

### ISSUE THREAD

**Issue by astwyg** [Lothiraldan/saltpad#159]
hi, everyone:

  i am trying deploy saltpad on my Falsk project, but when i open browser got an error from *createBrowserHistory.js:117*:

```
Uncaught (in promise) DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'http://login/' cannot be created in a document with origin 'http://127.0.0.1:8000'.
```

  but `npm run start` works fine, it seems something wrong with React-Route. Thank you any idea about this problem.

**Comment by Lothiraldan** [comment]
Hi @astwyg, which saltpad version did you tried to run? How did you tried to run it?

**Comment by astwyg** [comment]
thank you for responding @Lothiraldan  

i am using salt 2015.8.8, with saltpad 0.3.1

i just found this pair can ONLY work on embedded cherrypy...

when i config them , i tried to login , bug my **browser** send a XHR to `http://localhost:8000/login`.

my salt-master config is :

```
rest_cherrypy:
  port: 8000
  host: 0.0.0.0
  disable_ssl: true
  websockets: true
  cors_origin: '*'
  static: /home/ctyun/saltpad/static
  static_path: /static
  app: /home/ctyun/saltpad/templates/index.html
  app_path: /salt

external_auth:
  pam:
    salt:
    -  .*
    -  '@runner'
    -  '@wheel'
```

my saltpad config is :

```
{
    "API_URL": "localhost:8000",
    "SECURE_HTTP": false,
    "templates": {
    },
    "EAUTH": "pam",
    "FLAVOUR": "rest_cherrypy",
    "PATH_PREFIX": "/salt/"
}
```

will you please help me find out where goes bad?  tyvm. 

:)
