### ISSUE TITLE
Network Error issue when login saltpad

### ISSUE THREAD

**Issue by meagon** [Lothiraldan/saltpad#166]
I got   <b>Network Error </b>  when Login Salt-pad

**Comment by seamus-45** [comment]
I suspect that you should install git version of salt with **CORS** support, and configure salt api as documented:
```
rest_tornado:
  port: 5417
  host: 127.0.0.1
  disable_ssl: true
  websockets: True
  cors_origin: '*'
```

**Comment by Lothiraldan** [comment]
Hi @meagon are you sure the salt-api is accessible from the computer your browser is running on?
Could you follow the debug instructions here https://github.com/Lothiraldan/saltpad/blob/master/docs/debug.md to see if its helps?
If it still fails, could you please give us the version of saltpad, salt-master and salt-api + salt-api configuration, it will help us debug your problem.

**Comment by meagon** [comment]
my   Salt_API --version  

```shell
salt-api --version
salt-api 2016.3.0-572-g9f42882 (Boron)
```
AND   salt-master configuration 
```yaml

rest_cherrypy:
  debug: True
  disable_ssl: True
  port: 8000
  host: 0.0.0.0
  cors_origin: '*'
  static: /code/static
  static_path: /static
  app: /code/index.html
  app_path: /saltpad
  websockets: True


rest_tornado:
  debug: True
  disable_ssl: True
  port: 5417
  host: 0.0.0.0
  websockets: True
  cors_origin: '*'
  webhook_disable_auth: False

```

it all debug ok  with command line  curl ...

when i login in use firefox:
  it shows me  Network Error


[firefox Login](http://static.oschina.net/uploads/space/2016/0522/101306_T165_1016427.png)
![Uploading Screenshot from 2016-05-22 10:06:14.png…]()
